### PR TITLE
Implement join bar link. Fix redirect bug in login flow. Fix bug in public menus link.

### LINKED ISSUE #172: Direct link to join a bar
As a bar admin, I would like to have the option to send a unique link to people to join the bar, instead of the instance URL + the invite code.

Could be something like [base-URL]/bars/join?token=[invite-code] which upon visited, triggers the login flow and then the bar joining flow for the given bar.

### PR DESCRIPTION
**Pull request by Fra146**
### Closes #172
A new route (/invite/join/:invite) allows the user to join a bar by supplying the invite code in an URL parameter. This will display the normal join bar dialog, with an automatically set invite code.
If the user doesn't specify :invite, the bar join dialog will open but no invite code will be set.
In the bars list, when the bar invite code is visible, a clickable link allows the user to copy the invite link to the clipboard.
Bars ⋅ Bar Assistant 

Three strings are added to en_US.json, to tell the user if the link is successfully copied or not and for the button to actually join the bar (using "Join" instead of "Save" seemed more appropriate)

A new copy to clipboard function is also available in Utils.js

### Bug fixes

A new public menu route (/menu/:slug) would be the replacement for the old public menu route (/bars/:slug). This is because if a bar has its public link equivalent to "form" or "join", the hard-coded router route would overwrite them, rendering the menu useless.
To avoid invalidating QR codes, the old route (/bars/:slug) is still available as a legacy option. The bar settings and the generated QR codes are updated to work with the new route (/menu/:slug)

The login flow redirect is fixed, allowing users to be logged in and redirected to where they intended to go in the first place.

### CODE REVIEW

File: src/components/Bar/BarIndex.vue [hunk 1]
```diff
@@ -139,6 +142,13 @@ export default {
         this.refreshBars()
     },
     methods: {
+        copyInviteLinkToClipboard(invite_code) {
+            if (Utils.copyToClipboard(`${window.location.origin}/bars/join/${invite_code}`)) {
+                this.$toast.success(this.$t('bars.invite-link-copied'))
```
Comment (karlomikus) [inline src/components/Bar/BarIndex.vue:147]: Currently, only `default` and `error` should be used.
```suggestion
                this.$toast.default(this.$t('bars.invite-link-copied'))
```

**Comment by karlomikus** [comment]
Nice work, thank you very much 👍
